/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdProjectsRouteImport } from './routes/_chat.$environmentId.projects'
import { Route as ChatEnvironmentIdProjectsIndexRouteImport } from './routes/_chat.$environmentId.projects.index'
import { Route as ChatEnvironmentIdProjectsProjectIdThreadsRouteImport } from './routes/_chat.$environmentId.projects.$projectId.threads'
import { Route as ChatEnvironmentIdProjectsProjectIdTerminalRouteImport } from './routes/_chat.$environmentId.projects.$projectId.terminal'
import { Route as ChatEnvironmentIdProjectsProjectIdThreadsIndexRouteImport } from './routes/_chat.$environmentId.projects.$projectId.threads.index'
import { Route as ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRouteImport } from './routes/_chat.$environmentId.projects.$projectId.threads.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdProjectsRoute =
  ChatEnvironmentIdProjectsRouteImport.update({
    id: '/$environmentId/projects',
    path: '/$environmentId/projects',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatEnvironmentIdProjectsIndexRoute =
  ChatEnvironmentIdProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChatEnvironmentIdProjectsRoute,
  } as any)
const ChatEnvironmentIdProjectsProjectIdThreadsRoute =
  ChatEnvironmentIdProjectsProjectIdThreadsRouteImport.update({
    id: '/$projectId/threads',
    path: '/$projectId/threads',
    getParentRoute: () => ChatEnvironmentIdProjectsRoute,
  } as any)
const ChatEnvironmentIdProjectsProjectIdTerminalRoute =
  ChatEnvironmentIdProjectsProjectIdTerminalRouteImport.update({
    id: '/$projectId/terminal',
    path: '/$projectId/terminal',
    getParentRoute: () => ChatEnvironmentIdProjectsRoute,
  } as any)
const ChatEnvironmentIdProjectsProjectIdThreadsIndexRoute =
  ChatEnvironmentIdProjectsProjectIdThreadsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChatEnvironmentIdProjectsProjectIdThreadsRoute,
  } as any)
const ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRoute =
  ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => ChatEnvironmentIdProjectsProjectIdThreadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/$environmentId/projects': typeof ChatEnvironmentIdProjectsRouteWithChildren
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/$environmentId/projects/': typeof ChatEnvironmentIdProjectsIndexRoute
  '/$environmentId/projects/$projectId/terminal': typeof ChatEnvironmentIdProjectsProjectIdTerminalRoute
  '/$environmentId/projects/$projectId/threads': typeof ChatEnvironmentIdProjectsProjectIdThreadsRouteWithChildren
  '/$environmentId/projects/$projectId/threads/$threadId': typeof ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRoute
  '/$environmentId/projects/$projectId/threads/': typeof ChatEnvironmentIdProjectsProjectIdThreadsIndexRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/': typeof ChatIndexRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/$environmentId/projects': typeof ChatEnvironmentIdProjectsIndexRoute
  '/$environmentId/projects/$projectId/terminal': typeof ChatEnvironmentIdProjectsProjectIdTerminalRoute
  '/$environmentId/projects/$projectId/threads/$threadId': typeof ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRoute
  '/$environmentId/projects/$projectId/threads': typeof ChatEnvironmentIdProjectsProjectIdThreadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/projects': typeof ChatEnvironmentIdProjectsRouteWithChildren
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/_chat/$environmentId/projects/': typeof ChatEnvironmentIdProjectsIndexRoute
  '/_chat/$environmentId/projects/$projectId/terminal': typeof ChatEnvironmentIdProjectsProjectIdTerminalRoute
  '/_chat/$environmentId/projects/$projectId/threads': typeof ChatEnvironmentIdProjectsProjectIdThreadsRouteWithChildren
  '/_chat/$environmentId/projects/$projectId/threads/$threadId': typeof ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRoute
  '/_chat/$environmentId/projects/$projectId/threads/': typeof ChatEnvironmentIdProjectsProjectIdThreadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/providers'
    | '/settings/source-control'
    | '/$environmentId/projects'
    | '/draft/$draftId'
    | '/$environmentId/projects/'
    | '/$environmentId/projects/$projectId/terminal'
    | '/$environmentId/projects/$projectId/threads'
    | '/$environmentId/projects/$projectId/threads/$threadId'
    | '/$environmentId/projects/$projectId/threads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/providers'
    | '/settings/source-control'
    | '/'
    | '/draft/$draftId'
    | '/$environmentId/projects'
    | '/$environmentId/projects/$projectId/terminal'
    | '/$environmentId/projects/$projectId/threads/$threadId'
    | '/$environmentId/projects/$projectId/threads'
  id:
    | '__root__'
    | '/_chat'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/providers'
    | '/settings/source-control'
    | '/_chat/'
    | '/_chat/$environmentId/projects'
    | '/_chat/draft/$draftId'
    | '/_chat/$environmentId/projects/'
    | '/_chat/$environmentId/projects/$projectId/terminal'
    | '/_chat/$environmentId/projects/$projectId/threads'
    | '/_chat/$environmentId/projects/$projectId/threads/$threadId'
    | '/_chat/$environmentId/projects/$projectId/threads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/projects': {
      id: '/_chat/$environmentId/projects'
      path: '/$environmentId/projects'
      fullPath: '/$environmentId/projects'
      preLoaderRoute: typeof ChatEnvironmentIdProjectsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/projects/': {
      id: '/_chat/$environmentId/projects/'
      path: '/'
      fullPath: '/$environmentId/projects/'
      preLoaderRoute: typeof ChatEnvironmentIdProjectsIndexRouteImport
      parentRoute: typeof ChatEnvironmentIdProjectsRoute
    }
    '/_chat/$environmentId/projects/$projectId/threads': {
      id: '/_chat/$environmentId/projects/$projectId/threads'
      path: '/$projectId/threads'
      fullPath: '/$environmentId/projects/$projectId/threads'
      preLoaderRoute: typeof ChatEnvironmentIdProjectsProjectIdThreadsRouteImport
      parentRoute: typeof ChatEnvironmentIdProjectsRoute
    }
    '/_chat/$environmentId/projects/$projectId/terminal': {
      id: '/_chat/$environmentId/projects/$projectId/terminal'
      path: '/$projectId/terminal'
      fullPath: '/$environmentId/projects/$projectId/terminal'
      preLoaderRoute: typeof ChatEnvironmentIdProjectsProjectIdTerminalRouteImport
      parentRoute: typeof ChatEnvironmentIdProjectsRoute
    }
    '/_chat/$environmentId/projects/$projectId/threads/': {
      id: '/_chat/$environmentId/projects/$projectId/threads/'
      path: '/'
      fullPath: '/$environmentId/projects/$projectId/threads/'
      preLoaderRoute: typeof ChatEnvironmentIdProjectsProjectIdThreadsIndexRouteImport
      parentRoute: typeof ChatEnvironmentIdProjectsProjectIdThreadsRoute
    }
    '/_chat/$environmentId/projects/$projectId/threads/$threadId': {
      id: '/_chat/$environmentId/projects/$projectId/threads/$threadId'
      path: '/$threadId'
      fullPath: '/$environmentId/projects/$projectId/threads/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRouteImport
      parentRoute: typeof ChatEnvironmentIdProjectsProjectIdThreadsRoute
    }
  }
}

interface ChatEnvironmentIdProjectsProjectIdThreadsRouteChildren {
  ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRoute: typeof ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRoute
  ChatEnvironmentIdProjectsProjectIdThreadsIndexRoute: typeof ChatEnvironmentIdProjectsProjectIdThreadsIndexRoute
}

const ChatEnvironmentIdProjectsProjectIdThreadsRouteChildren: ChatEnvironmentIdProjectsProjectIdThreadsRouteChildren =
  {
    ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRoute:
      ChatEnvironmentIdProjectsProjectIdThreadsThreadIdRoute,
    ChatEnvironmentIdProjectsProjectIdThreadsIndexRoute:
      ChatEnvironmentIdProjectsProjectIdThreadsIndexRoute,
  }

const ChatEnvironmentIdProjectsProjectIdThreadsRouteWithChildren =
  ChatEnvironmentIdProjectsProjectIdThreadsRoute._addFileChildren(
    ChatEnvironmentIdProjectsProjectIdThreadsRouteChildren,
  )

interface ChatEnvironmentIdProjectsRouteChildren {
  ChatEnvironmentIdProjectsIndexRoute: typeof ChatEnvironmentIdProjectsIndexRoute
  ChatEnvironmentIdProjectsProjectIdTerminalRoute: typeof ChatEnvironmentIdProjectsProjectIdTerminalRoute
  ChatEnvironmentIdProjectsProjectIdThreadsRoute: typeof ChatEnvironmentIdProjectsProjectIdThreadsRouteWithChildren
}

const ChatEnvironmentIdProjectsRouteChildren: ChatEnvironmentIdProjectsRouteChildren =
  {
    ChatEnvironmentIdProjectsIndexRoute: ChatEnvironmentIdProjectsIndexRoute,
    ChatEnvironmentIdProjectsProjectIdTerminalRoute:
      ChatEnvironmentIdProjectsProjectIdTerminalRoute,
    ChatEnvironmentIdProjectsProjectIdThreadsRoute:
      ChatEnvironmentIdProjectsProjectIdThreadsRouteWithChildren,
  }

const ChatEnvironmentIdProjectsRouteWithChildren =
  ChatEnvironmentIdProjectsRoute._addFileChildren(
    ChatEnvironmentIdProjectsRouteChildren,
  )

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdProjectsRoute: typeof ChatEnvironmentIdProjectsRouteWithChildren
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdProjectsRoute: ChatEnvironmentIdProjectsRouteWithChildren,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
